spring:
#  sql:
#    init:
#      mode: never
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipes;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate.format_sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
